RStudio: A few more fixes, more to come
It seems that ICU is not being linked to when we link to libboost_locale.a (as happens for
postback and maybe others):

..
time_zone.cpp:(.text+0x2a): undefined reference to `icu_58::UnicodeString::UnicodeString(char const*)'
time_zone.cpp:(.text+0x33): undefined reference to `icu_58::TimeZone::createTimeZone(icu_58::UnicodeString const&)'
time_zone.cpp:(.text+0x41): undefined reference to `icu_58::UnicodeString::~UnicodeString()'
time_zone.cpp:(.text+0x6a): undefined reference to `icu_58::TimeZone::createDefault()'
time_zone.cpp:(.text+0x7e): undefined reference to `icu_58::UnicodeString::~UnicodeString()'

Adding `pkg-config --libs --cflags icu-uc icu-io` to the end of the link commandline for
postback fixes this. We need to either not use libboost_locale.a or add this.